// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      { let a, b; a in b; }
      { let a, b; a instanceof b; }
      { let a, b; a = b; }
      { let a, b; a + b; }
      { let a, b; a += b; }
      { let a, b; a - b; }
      { let a, b; a -= b; }
      { let a, b; a * b; }
      { let a, b; a *= b; }
      { let a, b; a ** b; }
      { let a, b; a **= b; }
      { let a, b; a / b; }
      { let a, b; a /= b; }
      { let a, b; a % b; }
      { let a, b; a %= b; }
      { let a, b; a << b; }
      { let a, b; a <<= b; }
      { let a, b; a >> b; }
      { let a, b; a >>= b; }
      { let a, b; a >>> b; }
      { let a, b; a >>>= b; }
      { let a, b; a & b; }
      { let a, b; a &= b; }
      { let a, b; a | b; }
      { let a, b; a |= b; }
      { let a, b; a ^ b; }
      { let a, b; a ^= b; }

      { let a, b; a == b; }
      { let a, b; a === b; }
      { let a, b; a != b; }
      { let a, b; a !== b; }
      { let a, b; a < b; }
      { let a, b; a <= b; }
      { let a, b; a > b; }
      { let a, b; a >= b; }
      { let a, b; a || b; }
      { let a, b; a && b; }
      { let a, b; a ^^ b; }
      
      { let a; a++; }
      { let a; ++a; }
      { let a; a--; }
      { let a; --a; }
      { let a; -a; }
      { let a; +a; }
      { let a; ~a; }
      { let a; !a; }
    `
  },
  options: {},
  result: {
    files: {
      'input.js': `
      { let a, b; a in b; }
      { let a, b; a instanceof b; }
      { let a, b; a = b; }
      { let a, b; a + b; }
      { let a, b; a += b; }
      { let a: number, b: number; a - b; }
      { let a?: number?: number?: number?: number?: number, b?: number?: number?: number?: number?: number; a -= b; }
      { let a: number, b: number; a * b; }
      { let a?: number?: number?: number?: number?: number, b?: number?: number?: number?: number?: number; a *= b; }
      { let a: number, b: number; a ** b; }
      { let a?: number?: number?: number?: number?: number, b?: number?: number?: number?: number?: number; a **= b; }
      { let a: number, b: number; a / b; }
      { let a?: number?: number?: number?: number?: number, b?: number?: number?: number?: number?: number; a /= b; }
      { let a: number, b: number; a % b; }
      { let a?: number?: number?: number?: number?: number, b?: number?: number?: number?: number?: number; a %= b; }
      { let a: number, b: number; a << b; }
      { let a: number, b: number?: number; a <<= b; }
      { let a: number, b: number; a >> b; }
      { let a, b; a >>= b; }
      { let a: number, b: number; a >>> b; }
      { let a, b; a >>>= b; }
      { let a: number, b: number; a & b; }
      { let a?: number?: number?: number?: number?: number, b?: number?: number?: number?: number?: number; a &= b; }
      { let a: number, b: number; a | b; }
      { let a?: number?: number?: number?: number?: number, b?: number?: number?: number?: number?: number; a |= b; }
      { let a: number, b: number; a ^ b; }
      { let a?: number?: number?: number?: number?: number, b?: number?: number?: number?: number?: number; a ^= b; }

      { let a, b; a == b; }
      { let a, b; a === b; }
      { let a, b; a != b; }
      { let a, b; a !== b; }
      { let a: number, b: number; a < b; }
      { let a: number, b: number; a <= b; }
      { let a: number, b: number; a > b; }
      { let a: number, b: number; a >= b; }
      { let a: boolean, b: boolean; a || b; }
      { let a: boolean, b: boolean; a && b; }
      { let a: number, b: number; a ^^ b; }
      
      { let a: number; a++; }
      { let a: number; ++a; }
      { let a: number; a--; }
      { let a: number; --a; }
      { let a; -a; }
      { let a; +a; }
      { let a: number; ~a; }
      { let a: number; !a; }
    `
    },
    metadata: {
      inferencePasses: 5
    }
  }
} as TestSpec
