// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      function f(x) {
        x.a.foo;
        x['a'].bar;
        x.b().foo;
        x['b']().bar;
        'z' in x;
      }    
    `
  },
  options: {},
  result: {
    files: {
      'input.js': `
function f(x: {readonly a: {readonly bar: any, readonly foo: any}, b(): {readonly bar: any, readonly foo: any}, z?: any}): void {
  x.a.foo;
  x['a'].bar;
  x.b().foo;
  x['b']().bar;
  'z' in x;
}
`
    },
    metadata: {
      inferencePasses: 2
    }
  }
} as TestSpec
