// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      function f3(x) {
        g3(1);
        g3(x);
      }
      
      function g3(x) {
        return x + 1;
      }
    `
  },
  options: {
    
  },
  result: {
    files: {
      'input.js': `
        function f3(x: number): void {
          g3(1);
          g3(x);
        }
        
        function g3(x: number): number {
          return x + 1;
        }
      `
    },
    metadata: {
      inferencePasses: 3
    }
  }
} as TestSpec
