// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  inputs: {
    'input.js': `
      function f5(s) {
        return s.length == 0 ? '' : s.substring(1);
      }
      
      function ff5(s) {
        return s.length == 0 ? '' : s;
      }
      
      function fff5(s) {
        return s.substring(1);
      }
      
      function g5(s) {
        return s ? s : '';
      }
      
      function h5(x) {
        if (ff5(x) == '' && g5(x) == '') {
          console.log('error');
        }
      }
      
      function i5(x1, x2) {
        if (x2.y) return x2.y.length;
        return x1 ? x1.y : null;
      }
    `
  },
  outputs: {
    'input.js': `
      function f5(s: string) {
        return s.length == 0 ? '' : s.substring(1);
      }
      
      function ff5(s: string): string {
        return s.length == 0 ? '' : s;
      }
      
      function fff5(s: string) {
        return s.substring(1);
      }
      
      function g5(s: string): string {
        return s ? s : '';
      }
      
      function h5(x: string): void {
        if (ff5(x) == '' && g5(x) == '') {
          console.log('error');
        }
      }
      
      function i5(x1?: {y: any}, x2: {y: string}) {
        if (x2.y) return x2.y.length;
        return x1 ? x1.y : null;
      }
    `
  },
  metadata: {
    inferencePasses: 4
  }
} as TestSpec
