// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `UPDATE_GOLDENS=1 npm run test`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  inputs: {
    'input.js': `
      function f3(x) {
        g3(1);
        g3(x);
      }
      
      function g3(x) {
        return x + 1;
      }
    `
  },
  outputs: {
    'input.js': `
      function f3(x: number): void {
        g3(1);
        g3(x);
      }
      
      function g3(x: number): number {
        return x + 1;
      }
    `
  },
  metadata: {
    inferencePasses: 3
  }
} as TestSpec
