// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      function f(x) {
        x.a == 1;
        x['a'] == '';
        x.b();
        x['b']();
        x.c = true;
        x['c'] = '';
      }    
    `
  },
  options: {},
  result: {
    files: {
      'input.js': `
function f(x: {readonly a: number, b(): void, c: boolean, readonly ['a']: number | string, ['b'](): void, ['c']: string}): void {
  x.a == 1;
  x['a'] == '';
  x.b();
  x['b']();
  x.c = true;
  x['c'] = '';
}
`
    },
    metadata: {
      inferencePasses: 3
    }
  }
} as TestSpec
