// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      (x) => typeof x == 'undefined';
      (x) => typeof x == 'string';
      (x) => typeof x == 'boolean';
      (x) => typeof x == 'number';
      (x) => typeof x == 'symbol';
    `
  },
  options: {},
  result: {
    files: {
      'input.js': `
      (x?: any) => typeof x == 'undefined';
      (x: string) => typeof x == 'string';
      (x: boolean) => typeof x == 'boolean';
      (x: number) => typeof x == 'number';
      (x: symbol) => typeof x == 'symbol';
    `
    },
    metadata: {
      inferencePasses: 2
    }
  }
} as TestSpec
