// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `UPDATE_GOLDENS=1 npm run test`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  inputs: {
    'input.js': `
      function f(xx, y) {
        var zz1;
        zz1 = z;
        zz1 = '';
      
        var zz2 = z;
        zz2 = '';
        return x + 2 + g(y);
      }
      
      function g(x) {
        return x * 2;
      }
    `
  },
  outputs: {
    'input.js': `
      function f(xx, y: number) {
        let zz1;
        zz1 = z;
        zz1 = '';
      
        let zz2 = z;
        zz2 = '';
        return x + 2 + g(y);
      }
      
      function g(x: number): number {
        return x * 2;
      }
    `
  },
  metadata: {
    inferencePasses: 3
  }
} as TestSpec
