// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'readonlies.js': `
      function f(x, y) {
        console.log(x.i);
        Object.assign(x, y, {a: '', b: 1, ['c']: true});
      }
      f({z: 1, a: ''}, {k: 1});
    `
  },
  options: {
    differentiateComputedProperties: true
  },
  result: {
    files: {
      'readonlies.js': `
      function f(x: {a?: string, b?: number, readonly i: any, k?: number, readonly z: number, ['c']: boolean}, y: {readonly k: number}): void {
        console.log(x.i);
        Object.assign(x, y, {a: '', b: 1, ['c']: true});
      }
      f({z: 1, a: ''}, {k: 1});
    `
    },
    metadata: {
      inferencePasses: 3
    }
  }
} as TestSpec
