// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      function f6(x) {
        return x && x.y(1) + x.y(1, 2);
      }
      
      function g6(x) {
        return x && x.y && x.y(1);
      }
          
          
    `
  },
  options: {},
  result: {
    files: {
      'input.js': `
      function f6(x?: {y(arg1: number, arg2?: number): any}) {
        return x && x.y(1) + x.y(1, 2);
      }
      
      function g6(x?: {readonly y?: (arg1: number) => boolean}): boolean {
        return x && x.y && x.y(1);
      }
          
          
    `
    },
    metadata: {
      inferencePasses: 3
    }
  }
} as TestSpec
