// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      function f(x) {
        x.a;
        x.b = 1;
        if (x.c) x.c();
        delete x.d;
      }

      function g(x) {
        f(x);
      } 
    `
  },
  options: {},
  result: {
    files: {
      'input.js': `
      function f(x: {readonly a: any, b: number, c?: () => void, d?: any}): void {
        x.a;
        x.b = 1;
        if (x.c) x.c();
        delete x.d;
      }

      function g(x: {readonly a: any, b: number, c?: () => void, d?: any}): void {
        f(x);
      } 
    `
    },
    metadata: {
      inferencePasses: 3
    }
  }
} as TestSpec
