// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      let a = {x: 1};
      let b = Object.create(a);
      let c = Object.create(a, {y: 2})
      let d = Object.create({}, a)

      let e = Object.create()
    `
  },
  options: {
    differentiateComputedProperties: true
  },
  result: {
    files: {
      'input.js': `
      let a: {x: number} = {x: 1};
      let b: {x: number} = Object.create(a);
      let c: {x: number, y: number} = Object.create(a, {y: 2})
      let d: {x: number} = Object.create({}, a)

      let e = Object.create()
    `
    },
    metadata: {
      inferencePasses: 2
    }
  }
} as TestSpec
