// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'foo.ts': `
      import {Bar, takeBar} from './bar';
      import * as bar from './bar';
      import * as baz from './baz';
      function foo(x) {
        takeBar(x);
        takeBar();

        bar.takeBar(1);
      }
      foo(new Bar());

      function babaz(x) {
        baz.a(x);
        baz.a(1);

        baz.b('');

        baz.c = '';
      }
    `,
    'bar.ts': `
      export class Bar {}
      export function takeBar(x) {}
    `,
    'baz.ts': `
      export default {
        a: a,
        b: function(x) {},
        c: 1
      }
      function a(x) {
        x.y.z();
      }
    `
  },
  options: {},
  result: {
    files: {
      'foo.ts': `
      import {Bar, takeBar} from './bar';
      import * as bar from './bar';
      import * as baz from './baz';
      function foo(x?: Bar): void {
        takeBar(x);
        takeBar();

        bar.takeBar(1);
      }
      foo(new Bar());

      function babaz(x): void {
        baz.a(x);
        baz.a(1);

        baz.b('');

        baz.c = '';
      }
    `,
      'bar.ts': `
      export class Bar {}
      export function takeBar(x?: Bar | number): void {}
    `,
      'baz.ts': `
      export default {
        a: a,
        b: function(x): void {},
        c: 1
      }
      function a(x: {readonly y: {z(): void}}): void {
        x.y.z();
      }
    `
    },
    metadata: {
      inferencePasses: 4
    }
  }
} as TestSpec
