// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'untransformable exports.js': `
      module.exports = {
        f() { return 1 },
        n: 1
      };
          
          
    `,
    'independent exports.js': `
      module.exports = {
        foo: f,
        g: g,
        n: n,
      };
      
      var n = 1;
      
      function f() {}
      function g() {}
      function h() {}
          
          
    `,
    'exported vars in multiple declaration are too complex.js': `
      module.exports = {
        a: a
      };
      var a = 1, b = 2;
          
          
    `
  },
  options: {},
  result: {
    files: {
      'untransformable exports.js': `
export default {
  f(): number {return 1},
  n: 1
};


`,
      'independent exports.js': `


export var n: number = 1;

function f(): void {}
export {f as foo};

export function g(): void {}
function h(): void {}


`,
      'exported vars in multiple declaration are too complex.js': `
export default {
  a: a
};
var a: number = 1, b: number = 2;


`
    },
    metadata: {
      inferencePasses: 2
    }
  }
} as TestSpec
