// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'untransformable exports.ts': `
      module.exports = {
        f() { return 1 },
        n: 1
      };
          
          
    `,
    'independent exports.ts': `
      module.exports = {
        id_foo: id_f,
        id_g: id_g,
        id_n: id_n,
      };
      
      var id_n = 1;
      
      function id_f() {}
      function id_g() {}
      function id_h() {}
    `,
    'exported default value.ts': `
      module.exports = a;
      var a = 1;
    `,
    'exported default function.ts': `
      module.exports = function(x) {};
    `,
    'exported default aliased function.ts': `
      module.exports = f;
      function f(x) {}
    `,
    'exported vars in multiple declaration are too complex.ts': `
      module.exports = {
        a: a
      };
      var a = 1, b = 2;
          
          
    `
  },
  options: {},
  result: {
    files: {
      'untransformable exports.ts': `
      export default {
        f(): number { return 1 },
        n: 1
      };
          
          
    `,
      'independent exports.ts': `
      
      
      export var id_n: number = 1;
      
      function id_f(): void {}
export {id_f as id_foo};

      export function id_g(): void {}
      function id_h(): void {}
    `,
      'exported default value.ts': `
      module.exports = a;
      var a: number = 1;
    `,
      'exported default function.ts': `
      export default function(x) {};
    `,
      'exported default aliased function.ts': `
      
      export default function f(x): void {}
    `,
      'exported vars in multiple declaration are too complex.ts': `
      export default {
        a: a
      };
      var a: number = 1, b: number = 2;
          
          
    `
    },
    metadata: {
      inferencePasses: 2
    }
  }
} as TestSpec
