// SEMI-AUTOGENERATED FILE, PLEASE ONLY EDIT INPUTS.
//
// REGENERATE OUTPUTS AND METADATA WITH `npm run update-specs`.

import {TestSpec} from '../../src/testing/test_spec';

export default {
  files: {
    'input.js': `
      var foo = require('foo');
      var a = foo.a;
      var b = foo.b;
      
      a(10) == '';
      b == 3;
      foo.c = 10;
          
          
    `
  },
  options: {},
  result: {
    files: {
      'input.js': `
import * as foo from 'foo';
var a: (arg1: number) => string = foo.a;
var b: number = foo.b;

a(10) == '';
b == 3;
foo.c = 10;


`,
      'node_modules/@types/foo/index.d.ts': `declare module "foo" {
  export function a(arg1: number): string;
  export const b: number;
  export let c: number;
}
`
    },
    metadata: {
      inferencePasses: 3
    }
  }
} as TestSpec
